import type { Product } from '../../../shared/types';

export const productCategories = ['Todas', 'Decorativas', 'Geek'] as const;

export const mockProducts: Product[] = [
  {
    id: 'bola-ocho',
    slug: 'bola-ocho',
    type: 'READY_MADE',
    name: 'Bola Ocho',
    category: 'Decorativas',
    description:
      'Alfombra tufting circular inspirada en la bola ocho, con textura alta y contraste grafico para espacios con actitud.',
    priceFrom: 170,
    basePriceCents: 17000,
    size: '60 x 60 cm',
    sizeCategory: 'MEDIUM',
    format: 'ROUND',
    image: '/rugs/bola-ocho.png',
    imageUrl: '/rugs/bola-ocho.png',
    colors: ['#0f0d0d', '#f4eadb', '#c7b899'],
    features: ['Hecha a mano', 'Formato circular', 'Alta densidad', 'Serie limitada'],
    material: 'Lana acrilica',
    productionTime: '12 a 18 dias',
    customizable: true,
    isCustomizable: true,
    isFeatured: true,
    isActive: true,
    motif: 'circles',
  },
  {
    id: 'gatos-yin-yang',
    slug: 'gatos-yin-yang',
    type: 'READY_MADE',
    name: 'Gatos Yin Yang',
    category: 'Decorativas',
    description:
      'Alfombra tufting ovalada con gatos en composicion yin yang, contraste blanco y negro y siluetas suaves.',
    priceFrom: 180,
    basePriceCents: 18000,
    size: 'A medida',
    sizeCategory: 'CUSTOM',
    format: 'ORGANIC',
    image: '/rugs/gatos-yin-yang.png',
    imageUrl: '/rugs/gatos-yin-yang.png',
    colors: ['#0f0d0d', '#f4eadb', '#c7b899'],
    features: ['Hecha a mano', 'Formato ovalado', 'Alto contraste', 'Personalizable'],
    material: 'Lana acrilica',
    productionTime: '12 a 18 dias',
    customizable: true,
    isCustomizable: true,
    isFeatured: true,
    isActive: true,
    motif: 'organic',
  },
  {
    id: 'sharingan',
    slug: 'sharingan',
    type: 'READY_MADE',
    name: 'Sharingan',
    category: 'Geek',
    description:
      'Alfombra tufting circular inspirada en un emblema rojo y negro de estetica anime, con lineas definidas y alto impacto visual.',
    priceFrom: 180,
    basePriceCents: 18000,
    size: 'A medida',
    sizeCategory: 'CUSTOM',
    format: 'ROUND',
    image: '/rugs/sharingan.png',
    imageUrl: '/rugs/sharingan.png',
    colors: ['#b40000', '#0f0d0d', '#5a0808'],
    features: ['Hecha a mano', 'Formato circular', 'Diseno geek', 'Alto contraste'],
    material: 'Lana acrilica',
    productionTime: '12 a 18 dias',
    customizable: true,
    isCustomizable: true,
    isFeatured: true,
    isActive: true,
    motif: 'circles',
  },
];
