import type { Product } from '../../../shared/types';

export const productCategories = [
  'Todas',
  'Geométricas',
  'Minimalistas',
  'Orgánicas',
  'Decorativas',
  'Personalizadas'
] as const;

export const mockProducts: Product[] = [
  {
    id: 'bola-ocho',
    slug: 'bola-ocho',
    type: 'READY_MADE',
    name: 'Bola Ocho',
    category: 'Decorativas',
    description:
      'Alfombra tufting circular inspirada en la bola ocho, con textura alta y contraste grafico para espacios con actitud.',
    priceFrom: 170,
    basePriceCents: 17000,
    size: '60 x 60 cm',
    sizeCategory: 'MEDIUM',
    format: 'ROUND',
    image: '/rugs/bola-ocho.png',
    imageUrl: '/rugs/bola-ocho.png',
    colors: ['#0f0d0d', '#f4eadb', '#c7b899'],
    features: ['Hecha a mano', 'Formato circular', 'Alta densidad', 'Serie limitada'],
    material: 'Lana acrilica',
    productionTime: '12 a 18 dias',
    customizable: true,
    isCustomizable: true,
    isFeatured: true,
    isActive: true,
    motif: 'circles'
  },
  {
    id: '1',
    slug: 'ondas-abstractas',
    type: 'READY_MADE',
    name: 'Ondas Abstractas',
    category: 'Decorativas',
    description:
      'Alfombra tufting hecha a mano con ondas libres, volumen suave y acabado premium para espacios con personalidad.',
    priceFrom: 150,
    basePriceCents: 15000,
    size: '100 x 80 cm',
    sizeCategory: 'MEDIUM',
    format: 'ORGANIC',
    image: '',
    imageUrl: '',
    colors: ['#1d2b53', '#f97316', '#db5c91'],
    features: ['Hecha a mano', 'Material premium', 'Personalizable', 'Base antiderrapante'],
    material: 'Lana acrilica',
    productionTime: '12 a 18 dias',
    customizable: true,
    isCustomizable: true,
    isFeatured: true,
    isActive: true,
    motif: 'waves'
  },
  {
    id: '2',
    slug: 'geometria-moderna',
    type: 'READY_MADE',
    name: 'Geometría Moderna',
    category: 'Geométricas',
    description:
      'Composición de bloques geométricos con contraste elegante, pensada para salas, estudios y rincones creativos.',
    priceFrom: 160,
    basePriceCents: 16000,
    size: '100 x 80 cm',
    sizeCategory: 'MEDIUM',
    format: 'RECTANGULAR',
    image: '',
    imageUrl: '',
    colors: ['#17324d', '#d8782e', '#f3dfbf'],
    features: ['Cortes definidos', 'Lana acrílica suave', 'Alta densidad', 'Serie limitada'],
    material: 'Lana acrilica',
    productionTime: '12 a 18 dias',
    customizable: true,
    isCustomizable: true,
    isFeatured: true,
    isActive: true,
    motif: 'geometric'
  },
  {
    id: '3',
    slug: 'terreno-natural',
    type: 'READY_MADE',
    name: 'Terreno Natural',
    category: 'Orgánicas',
    description:
      'Formas inspiradas en mapas de tierra, fibras cálidas y una paleta serena para interiores naturales.',
    priceFrom: 140,
    basePriceCents: 14000,
    size: '90 x 70 cm',
    sizeCategory: 'MEDIUM',
    format: 'ORGANIC',
    image: '',
    imageUrl: '',
    colors: ['#2f3f2f', '#b5884c', '#f4eadb'],
    features: ['Textura mullida', 'Diseño orgánico', 'Paleta natural', 'Borde reforzado'],
    material: 'Lana acrilica',
    productionTime: '12 a 18 dias',
    customizable: true,
    isCustomizable: true,
    isFeatured: false,
    isActive: true,
    motif: 'organic'
  },
  {
    id: '4',
    slug: 'circulos-organicos',
    type: 'READY_MADE',
    name: 'Círculos Orgánicos',
    category: 'Orgánicas',
    description:
      'Pieza circular con capas tonales y ritmo suave, ideal para vestir espacios pequeños con una presencia escultórica.',
    priceFrom: 130,
    basePriceCents: 13000,
    size: '60 x 60 cm',
    sizeCategory: 'MEDIUM',
    format: 'ROUND',
    image: '',
    imageUrl: '',
    colors: ['#31482f', '#d9a05c', '#e9b2a4'],
    features: ['Formato circular', 'Acabado elevado', 'Colores a elección', 'Base firme'],
    material: 'Lana acrilica',
    productionTime: '12 a 18 dias',
    customizable: true,
    isCustomizable: true,
    isFeatured: false,
    isActive: true,
    motif: 'circles'
  },
  {
    id: '5',
    slug: 'arcos-y-lineas',
    type: 'READY_MADE',
    name: 'Arcos y Líneas',
    category: 'Minimalistas',
    description:
      'Arcos gráficos sobre base clara, una alfombra sobria con gesto artístico para ambientes contemporáneos.',
    priceFrom: 150,
    basePriceCents: 15000,
    size: '80 x 120 cm',
    sizeCategory: 'MEDIUM',
    format: 'RECTANGULAR',
    image: '',
    imageUrl: '',
    colors: ['#111111', '#f2e7d5', '#9a4b35'],
    features: ['Minimalista', 'Fácil de combinar', 'Trazo gráfico', 'Hecha por encargo'],
    material: 'Lana acrilica',
    productionTime: '12 a 18 dias',
    customizable: true,
    isCustomizable: true,
    isFeatured: false,
    isActive: true,
    motif: 'arches'
  },
  {
    id: '6',
    slug: 'bruma-suave',
    type: 'FULL_CUSTOM',
    name: 'Bruma Suave',
    category: 'Personalizadas',
    description:
      'Base abstracta de tonos suaves preparada para adaptar medidas, colores y formas al espacio del cliente.',
    priceFrom: 180,
    basePriceCents: 18000,
    size: 'A medida',
    sizeCategory: 'CUSTOM',
    format: 'CUSTOM',
    image: '',
    imageUrl: '',
    colors: ['#6f8a9b', '#d8c7b1', '#b96f73'],
    features: ['100% personalizable', 'Moodboard incluido', 'Aprobación previa', 'Medidas flexibles'],
    material: 'Lana acrilica',
    productionTime: 'Bajo analisis',
    customizable: true,
    isCustomizable: true,
    isFeatured: true,
    isActive: true,
    motif: 'soft'
  }
];
